# Generated by Django 3.2.5 on 2021-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
    ]
