# Generated by Django 3.2.5 on 2021-07-15 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_list_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_completed',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 13, 12, 43, 618759, tzinfo=utc)),
        ),
    ]
