# Generated by Django 3.2.5 on 2021-07-19 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_list_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 19, 51, 30, 77339)),
        ),
    ]
